resources:
  - ../../base
  - service.yaml
  - ingress.yaml
  - hpa.yaml

patchesStrategicMerge:
  - deployment_patch.yaml

commonLabels:
  app: translation-api
  
  
# expects files to be in the same directory
secretGenerator:
  - name: redis-secret
    files:
      - translation-redis-truststore.jks
