<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>eu.europeana.api</groupId>
		<artifactId>translation-api</artifactId>
		<version>0.1.3-SNAPSHOT</version>
	</parent>
	<artifactId>translation-service-hybrid</artifactId>
	<name>translation-service-hybrid</name>
	<description>The Java APIs for an hybrid language detection service (part of Translation API)</description>

	<properties>
		<sonar.coverage.jacoco.xmlReportPaths>${basedir}/../${aggregate.report.xml}</sonar.coverage.jacoco.xmlReportPaths>	
	</properties>

	<dependencies>
		<dependency>
			<groupId>eu.europeana.api</groupId>
			<artifactId>translation-service-common</artifactId>
			<version>0.1.3-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>eu.europeana.api</groupId>
			<artifactId>translation-service-tika</artifactId>
			<version>0.1.3-SNAPSHOT</version>
		</dependency> 
	</dependencies>
</project>
