resources:
  - deployment.yaml

commonLabels:
  app: translation-api

# expects files to be in the same directory
secretGenerator:
  - name: translation-api-secret
    files:
      - translation.user.properties
  - name: google-auth-secret
    files:
      - google-auth.json

#generate config mapping for log4j2.xml file
configMapGenerator:
  - name: log4j2-properties
    files:
      - log4j2-spring.xml
  - name: translation-services-config-json
    files:
      - translation_service_configuration.json    
  - name: pangeanic-tresholds-properties
    files:
      - pangeanic_language_thresholds.properties    